query PullRequestThreads(
  $owner: String!,
  $name: String!,
  $number: Int!,
  $after: String
) {
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
      id
      number
      title
      author { login avatarUrl }

      reviewThreads(first: 50, after: $after) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          id
          isResolved
          isOutdated
          path
          line
          startLine
          originalLine
          originalStartLine
          diffSide
          startDiffSide
          comments(first: 50) {
            pageInfo {
              hasNextPage
              endCursor
            }
            nodes {
              id
              databaseId
              body
              bodyText
              createdAt
              lastEditedAt
              author { login avatarUrl }
              authorAssociation
              diffHunk
              path
              line
              originalLine
              commit {
                oid
                authoredDate
                author {
                  name
                  email
                  user { login avatarUrl }
                }
              }
              pullRequestReview {
                id
                state
                submittedAt
                author { login avatarUrl }
              }
            }
          }
        }
      }
    }
  }
  rateLimit {
    cost
    remaining
    resetAt
  }
}
